services:

  traefik:
    image: traefik:v3.6

  php:
    depends_on:
      - traefik
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_DATABASE: "${DB_DATABASE:-laravel}"
      MYSQL_USER: "${DB_USERNAME:-laravel}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-secret}"

  queue:
    command: ["php", "artisan", "queue:work", "--sleep=3", "--tries=3", "--max-time=3600"]
    depends_on:
      - mysql

  scheduler:
    command: ["php", "artisan", "schedule:work"]
    depends_on:
      - mysql